export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";

export const REQUEST_PROJECTS = "REQUEST_PROJECTS";
export const RECEIVE_PROJECTS = "RECEIVE_PROJECTS";

export const SET_ACTIVE_MENU_ITEM_V = "SET_ACTIVE_MENU_ITEM_V";
export const SET_ACTIVE_MENU_ITEM_H = "SET_ACTIVE_MENU_ITEM_H";

export const SET_ITEMS = "SET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const EDIT_ITEM_FIELD = "EDIT_ITEM_FIELD";
export const REGISTER_DAILY_WORK = "REGISTER_DAILY_WORK";

export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR";
