export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const RECEIVE_LOGIN = "RECEIVE_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";

export const REQUEST_PROJECTS = "REQUEST_PROJECTS";
export const RECEIVE_PROJECTS = "RECEIVE_PROJECTS";

export const SET_ACTIVE_MENU_ITEM_V = "SET_ACTIVE_MENU_ITEM_V";
export const SET_ACTIVE_MENU_ITEM_H = "SET_ACTIVE_MENU_ITEM_H";

export const SET_RECORDS = "SET_RECORDS";
export const ADD_RECORD = "ADD_RECORD";
export const EDIT_RECORD_FIELD = "EDIT_RECORD_FIELD";
export const SET_WORKITEM_DATE = "SET_WORKITEM_DATE";
export const SET_NEW_RECORD_START_TIME = "SET_NEW_RECORD_START_TIME";

export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR";
